"""Database update1

Revision ID: 20d6c1056560
Revises: 9f9426641b8f
Create Date: 2024-01-08 21:06:19.766432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d6c1056560'
down_revision: Union[str, None] = '9f9426641b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pereval_added', 'status')
    # ### end Alembic commands ###
