"""Database update3

Revision ID: 679f03f6fd06
Revises: 330d1ace2d52
Create Date: 2024-01-09 12:18:40.684991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679f03f6fd06'
down_revision: Union[str, None] = '330d1ace2d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pereval_added', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pereval_added', 'status', ['status_id'], ['id'])
    op.drop_column('pereval_added', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pereval_added', type_='foreignkey')
    op.drop_column('pereval_added', 'status_id')
    op.drop_table('status')
    # ### end Alembic commands ###
